// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0IazZaXXbeCtiIoH9bhL3XEakrQGEnE',
    appId: '1:411722774920:web:977541e0d12513efb7623d',
    messagingSenderId: '411722774920',
    projectId: 'chat-app-b7562',
    authDomain: 'chat-app-b7562.firebaseapp.com',
    storageBucket: 'chat-app-b7562.appspot.com',
    measurementId: 'G-VW09BD8FPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK9UWol1C9uyO3cFSyKism_diMFHO-x2Y',
    appId: '1:411722774920:android:730699849e1bdaaeb7623d',
    messagingSenderId: '411722774920',
    projectId: 'chat-app-b7562',
    storageBucket: 'chat-app-b7562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrVDHT0xPyuZMVak3ACJ1zuRnIR2mp_4',
    appId: '1:411722774920:ios:23424e43af905783b7623d',
    messagingSenderId: '411722774920',
    projectId: 'chat-app-b7562',
    storageBucket: 'chat-app-b7562.appspot.com',
    iosClientId: '411722774920-bio23bmpccq2fc5cssk28shejepvupk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
